version: '3' # １行目はdocker-compose.yml のフォーマットバージョン https://docs.docker.com/compose/compose-file/

services: # 起動するコンテナの設定を定義する
  mysql:
    image: mysql:5.7 # イメージ（mysqlリポジトリ：5.7タグ）をビルド
    container_name: rails_mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    environment: # userとpwを1組ずつ定義する必要あり。
      MYSQL_ROOT_USE: root #環境変数を定義
      MYSQL_ROOT_PASSWORD: root # 環境変数を定義
      MYSQL_EXTERNAL_USE: external
      MYSQL_EXTERNAL_PASSWORD: external

  rails: # コンテナの名前として任意で設定できる
    build:
      context: ./rails # ビルドするディレクトリを指定
      dockerfile: Dockerfile # ビルドするDockerfileを指定
    image: kthiro/rails:1.1 # イメージのリポジトリ名：タグ名を指定
    container_name: rails # コンテナ名を指定
    command: /bin/bash # (todo)とりあえずでしかない。。。
    expose: # コンテナ間通信するために必要
      - "3000"
    ports:
      - "3000:3000" # ホストマシンの3000ポートにアクセスきたら、コンテナの3000ポートにポートフォワーディング
    volumes:
      - ./rails/:/rails_app:cached # ホストOSのrailsディレクトリを、コンテナの/appにバインドマウント
    depends_on: # Railsコンテナを起動する前に、mysqlコンテナを起動する
      - "mysql"
    tty: true # インタラクティブなコマンド入力を可能にするための設定
    stdin_open: true # インタラクティブなコマンド入力を可能にするための設定

  vuejs:
    build:
      context: ./vuejs
      dockerfile: Dockerfile
    image: kthiro/vuejs:1.4
    container_name: vue
    command: /bin/bash # (todo)とりあえずでしかない。。。
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./vuejs/:/vue_app:cached
    depends_on:
      - "rails"
    tty: true
    stdin_open: true
